server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  web:
    resources:
      cache: # 页面静态文件缓存
        cachecontrol:
          cache-private: true
          must-revalidate: true
          max-age: 36000
          cache-public: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/home?characterEncoding=UTF-8&useSSL=false  # 设置字符编码utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver  # tomcat 8.0+
  sql:
    init:
      encoding: UTF-8
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
